export const GENRES_LIST = [
    { id: '1', name: 'Action', russian: 'Экшен' },
    { id: '2', name: 'Adventure', russian: 'Приключения' },
    { id: '3', name: 'Cars', russian: 'Машины' },
    { id: '4', name: 'Comedy', russian: 'Комедия' },
    { id: '5', name: 'Dementia', russian: 'Безумие' },
    { id: '6', name: 'Demons', russian: 'Демоны' },
    { id: '7', name: 'Mystery', russian: 'Детектив' },
    { id: '8', name: 'Drama', russian: 'Драма' },
    { id: '9', name: 'Ecchi', russian: 'Этти' },
    { id: '10', name: 'Fantasy', russian: 'Фэнтези' },
    { id: '11', name: 'Game', russian: 'Игры' },
    { id: '12', name: 'Hentai', russian: 'Хентай' },
    { id: '13', name: 'Historical', russian: 'Исторический' },
    { id: '14', name: 'Horror', russian: 'Ужасы' },
    { id: '15', name: 'Kids', russian: 'Детское' },
    { id: '16', name: 'Magic', russian: 'Магия' },
    { id: '17', name: 'Martial Arts', russian: 'Боевые искусства' },
    { id: '18', name: 'Mecha', russian: 'Меха' },
    { id: '19', name: 'Music', russian: 'Музыка' },
    { id: '20', name: 'Parody', russian: 'Пародия' },
    { id: '21', name: 'Samurai', russian: 'Самураи' },
    { id: '22', name: 'Romance', russian: 'Романтика' },
    { id: '23', name: 'School', russian: 'Школа' },
    { id: '24', name: 'Sci-Fi', russian: 'Фантастика' },
    { id: '25', name: 'Shoujo', russian: 'Сёдзе' },
    { id: '26', name: 'Shoujo Ai', russian: 'Сёдзе-ай' },
    { id: '27', name: 'Shounen', russian: 'Сёнен' },
    { id: '28', name: 'Shounen Ai', russian: 'Сёнен-ай' },
    { id: '29', name: 'Space', russian: 'Космос' },
    { id: '30', name: 'Sports', russian: 'Спорт' },
    { id: '31', name: 'Super Power', russian: 'Супер сила' },
    { id: '32', name: 'Vampire', russian: 'Вампиры' },
    { id: '33', name: 'Yaoi', russian: 'Яой' },
    { id: '34', name: 'Yuri', russian: 'Юри' },
    { id: '35', name: 'Harem', russian: 'Гарем' },
    { id: '36', name: 'Slice of Life', russian: 'Повседневность' },
    { id: '37', name: 'Supernatural', russian: 'Сверхъестественное' },
    { id: '38', name: 'Military', russian: 'Военное' },
    { id: '39', name: 'Police', russian: 'Полиция' },
    { id: '40', name: 'Psychological', russian: 'Психологическое' },
    { id: '41', name: 'Thriller', russian: 'Триллер' },
    { id: '42', name: 'Seinen', russian: 'Сейнен' },
    { id: '43', name: 'Josei', russian: 'Дзёсей' }
].sort((a, b) => a.russian.localeCompare(b.russian));

export const THEMES_LIST = [
    { id: '143', name: 'Anthropomorphic', russian: 'Антропоморфизм' },
    { id: '17', name: 'Martial Arts', russian: 'Боевые искусства' },
    { id: '32', name: 'Vampire', russian: 'Вампиры' },
    { id: '103', name: 'Video Game', russian: 'Видеоигры' },
    { id: '38', name: 'Military', russian: 'Военное' },
    { id: '104', name: 'Adult Cast', russian: 'Взрослые персонажи' },
    { id: '141', name: 'Survival', russian: 'Выживание' },
    { id: '35', name: 'Harem', russian: 'Гарем' },
    { id: '3', name: 'Racing', russian: 'Гонки' },
    { id: '197', name: 'Urban Fantasy', russian: 'Городское фэнтези' },
    { id: '112', name: 'Gag Humor', russian: 'Гэг-юмор' },
    { id: '39', name: 'Detective', russian: 'Детектив' },
    { id: '105', name: 'Gore', russian: 'Жестокость' },
    { id: '134', name: 'Childcare', russian: 'Забота о детях' },
    { id: '198', name: 'Villainess', russian: 'Злодейка' },
    { id: '146', name: 'High Stakes Game', russian: 'Игра с высокими ставками' },
    { id: '145', name: 'Idols (Female)', russian: 'Идолы (Жен.)' },
    { id: '150', name: 'Idols (Male)', russian: 'Идолы (Муж.)' },
    { id: '108', name: 'Visual Arts', russian: 'Изобразительное искусство' },
    { id: '142', name: 'Performing Arts', russian: 'Исполнительское искусство' },
    { id: '13', name: 'Historical', russian: 'Исторический' },
    { id: '130', name: 'Isekai', russian: 'Исэкай' },
    { id: '140', name: 'Iyashikei', russian: 'Иясикэй' },
    { id: '102', name: 'Team Sports', russian: 'Командный спорт' },
    { id: '29', name: 'Space', russian: 'Космос' },
    { id: '144', name: 'Crossdressing', russian: 'Кроссдрессинг' },
    { id: '137', name: 'Otaku Culture', russian: 'Культура отаку' },
    { id: '107', name: 'Love Polygon', russian: 'Любовный многоугольник' },
    { id: '135', name: 'Magical Sex Shift', russian: 'Магическая смена пола' },
    { id: '124', name: 'Mahou Shoujo', russian: 'Махо-сёдзё' },
    { id: '147', name: 'Medical', russian: 'Медицина' },
    { id: '18', name: 'Mecha', russian: 'Меха' },
    { id: '6', name: 'Mythology', russian: 'Мифология' },
    { id: '19', name: 'Music', russian: 'Музыка' },
    { id: '149', name: 'Educational', russian: 'Образовательное' },
    { id: '138', name: 'Organized Crime', russian: 'Организованная преступность' },
    { id: '20', name: 'Parody', russian: 'Пародия' },
    { id: '148', name: 'Pets', russian: 'Питомцы' },
    { id: '40', name: 'Psychological', russian: 'Психологическое' },
    { id: '111', name: 'Time Travel', russian: 'Путешествие во времени' },
    { id: '139', name: 'Workplace', russian: 'Работа' },
    { id: '125', name: 'Reverse Harem', russian: 'Реверс-гарем' },
    { id: '106', name: 'Reincarnation', russian: 'Реинкарнация' },
    { id: '151', name: 'Love Status Quo', russian: 'Романтический подтекст' },
    { id: '21', name: 'Samurai', russian: 'Самураи' },
    { id: '118', name: 'Combat Sports', russian: 'Спортивные единоборства' },
    { id: '11', name: 'Strategy Game', russian: 'Стратегические игры' },
    { id: '31', name: 'Super Power', russian: 'Супер сила' },
    { id: '114', name: 'Award Winning', russian: 'Удостоено наград' },
    { id: '131', name: 'Delinquents', russian: 'Хулиганы' },
    { id: '119', name: 'CGDCT', russian: 'CGDCT' },
    { id: '23', name: 'School', russian: 'Школа' },
    { id: '136', name: 'Showbiz', russian: 'Шоу-бизнес' },
].sort((a, b) => a.russian.localeCompare(b.russian));
